export type User = {
	external_id: string;
	first_name: string;
	last_name: string;
	email_address: string[];
	phone_number: string[];
	web3_wallet: string[];
	username: string;
	password: string;
	password_digest: string;
	password_hasher: string;
	skip_password_checks: boolean;
	skip_password_requirement: boolean;
	totp_secret: string;
	backup_codes: string[];
	public_metadata: any;
	private_metadata: any;
	unsafe_metadata: any;
	delete_self_enabled: boolean;
	legal_accepted_at: string;
	skip_legal_checks: boolean;
	create_organization_enabled: boolean;
	create_organizations_limit: number;
	created_at: string;
};
